-- Generated from Noctalia semantic roles.
vim.cmd("highlight clear")
vim.o.termguicolors = true
vim.o.background = "{{ mode }}"
vim.g.colors_name = "noctalia"
vim.api.nvim_set_hl(0, "Normal", { fg = "{{ colors.on_surface.default.hex }}", bg = "{{ colors.surface.default.hex }}" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "{{ colors.on_surface.default.hex }}", bg = "{{ colors.surface_container.default.hex }}" })
vim.api.nvim_set_hl(0, "FloatBorder", { fg = "{{ colors.outline.default.hex }}", bg = "{{ colors.surface_container.default.hex }}" })
vim.api.nvim_set_hl(0, "Comment", { fg = "{{ colors.outline.default.hex }}" })
vim.api.nvim_set_hl(0, "Constant", { fg = "{{ colors.tertiary.default.hex }}" })
vim.api.nvim_set_hl(0, "String", { fg = "{{ colors.secondary.default.hex }}" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "{{ colors.on_surface.default.hex }}" })
vim.api.nvim_set_hl(0, "Function", { fg = "{{ colors.primary.default.hex }}" })
vim.api.nvim_set_hl(0, "Statement", { fg = "{{ colors.primary.default.hex }}" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "{{ colors.tertiary.default.hex }}" })
vim.api.nvim_set_hl(0, "Type", { fg = "{{ colors.secondary.default.hex }}" })
vim.api.nvim_set_hl(0, "Special", { fg = "{{ colors.tertiary.default.hex }}" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "{{ colors.outline.default.hex }}" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "{{ colors.outline.default.hex }}" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "{{ colors.primary.default.hex }}" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "{{ colors.surface_container_low.default.hex }}" })
vim.api.nvim_set_hl(0, "Visual", { fg = "{{ colors.on_secondary_container.default.hex }}", bg = "{{ colors.secondary_container.default.hex }}" })
vim.api.nvim_set_hl(0, "Search", { fg = "{{ colors.on_tertiary_container.default.hex }}", bg = "{{ colors.tertiary_container.default.hex }}" })
vim.api.nvim_set_hl(0, "IncSearch", { fg = "{{ colors.on_primary.default.hex }}", bg = "{{ colors.primary.default.hex }}" })
vim.api.nvim_set_hl(0, "Pmenu", { fg = "{{ colors.on_surface.default.hex }}", bg = "{{ colors.surface_container.default.hex }}" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "{{ colors.on_primary.default.hex }}", bg = "{{ colors.primary.default.hex }}" })
vim.api.nvim_set_hl(0, "StatusLine", { fg = "{{ colors.on_surface.default.hex }}", bg = "{{ colors.surface_container_high.default.hex }}" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "{{ colors.outline.default.hex }}", bg = "{{ colors.surface_container.default.hex }}" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "{{ colors.outline.default.hex }}" })
vim.api.nvim_set_hl(0, "ErrorMsg", { fg = "{{ colors.error.default.hex }}" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "{{ colors.error.default.hex }}" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "{{ colors.tertiary.default.hex }}" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "{{ colors.secondary.default.hex }}" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "{{ colors.primary.default.hex }}" })
vim.api.nvim_set_hl(0, "DiffAdd", { fg = "{{ colors.on_secondary_container.default.hex }}", bg = "{{ colors.secondary_container.default.hex }}" })
vim.api.nvim_set_hl(0, "DiffChange", { fg = "{{ colors.on_tertiary_container.default.hex }}", bg = "{{ colors.tertiary_container.default.hex }}" })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = "{{ colors.on_error_container.default.hex }}", bg = "{{ colors.error_container.default.hex }}" })
vim.api.nvim_set_hl(0, "Title", { fg = "{{ colors.primary.default.hex }}" })
vim.api.nvim_set_hl(0, "Directory", { fg = "{{ colors.primary.default.hex }}" })
vim.api.nvim_set_hl(0, "MatchParen", { fg = "{{ colors.on_primary_container.default.hex }}", bg = "{{ colors.primary_container.default.hex }}" })
